language: php

php:
  - 7.1
  - 7.2

install:
  - travis_retry composer require php-coveralls/php-coveralls:^2.0@stable

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
